name: Exyconn Tracker For Print fast Node Js Backend Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/party-wings-backend:latest

      - name: Check Node.js version in built image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/party-wings-backend:latest
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/party-wings-backend:latest node -v
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/party-wings-backend:latest npm -v

      - name: Deploy via SSH and Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/party-wings-backend:latest
            docker stop party-wings-backend || true
            docker rm party-wings-backend || true
            docker run -d --name party-wings-backend -p 4005:4005 --restart=always ${{ secrets.DOCKERHUB_USERNAME }}/party-wings-backend:latest